### ISSUE TITLE
Proper function input

### ISSUE THREAD

**Issue by matugol** [SwissAndOr/Advanced-Graphing-Calculator#15]
Users should have the option to change in between JavaScript input (like it is now) and our custom input, which would work with what normally would be considered a function on paper.

**Comment by etillison3350** [comment]
i.e. remove the need for `Math`, among other things

**Comment by etillison3350** [comment]
This is almost complete; we just need the option to switch to javascript (maybe?)

**Comment by matugol** [comment]
No. We'll have Python scripting that has nothing to do with the function strings.
