### ISSUE TITLE
Faster repainting & no useless repainting and allowing edits while calculating

### ISSUE THREAD

**Issue by etillison3350** [SwissAndOr/Advanced-Graphing-Calculator#5]
- Improve graphing algorithms and methods in order to make the graphing time shorter
- Don't repaint the entire graph whenever the window is moved
- Add a progress bar to the graphing process and allow the user to do things while it's graphing

**Comment by matugol** [comment]
I'm pretty sure this is mostly solved right? If so just close this when you see it.
